[2023-09-22 16:34:12,258] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:34:14,557] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:34:14] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:34:16,999] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:34:16] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:34:20,664] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:34:20] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:34:21,649] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:34:21] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:03,278] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:03] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:09,663] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:09] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:09,926] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:09] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:11,779] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:11] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:12,093] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:12] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:39,900] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:39,901] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:44,062] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:44] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:44,324] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:44] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:47,548] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:47] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:52,743] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:52] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:53,065] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:53] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:54,731] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:54] "OPTIONS /produto/deletar/Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:38:55,043] INFO deletar_produto() L188  Tentando excluir produto Harry Potter e o Prisioneiro de Azkaban - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\projeto\backend\app.py L188 
[2023-09-22 16:38:55,046] INFO deletar_produto() L190  Produto Harry Potter e o Prisioneiro de Azkaban excluído com sucesso - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\projeto\backend\app.py L190 
[2023-09-22 16:38:55,047] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:38:55] "DELETE /produto/deletar/Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:30,026] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:30] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:36,184] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:36] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:36,494] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:36] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:39,116] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:39] "OPTIONS /produto/deletar/Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:39,426] INFO deletar_produto() L188  Tentando excluir produto Harry Potter e o Prisioneiro de Azkaban - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\projeto\backend\app.py L188 
[2023-09-22 16:39:39,432] INFO deletar_produto() L190  Produto Harry Potter e o Prisioneiro de Azkaban excluído com sucesso - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\projeto\backend\app.py L190 
[2023-09-22 16:39:39,432] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:39] "DELETE /produto/deletar/Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:40,628] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:40] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:40,946] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:40] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:43,313] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:43] "POST /swagger HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:45,342] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:45] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:39:45,661] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:39:45] "[35m[1mGET /produto/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:40:10,169] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:40:10] "GET /swagger?nome=Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:40:16,458] ERROR log_exception() L1414 Exception on /swagger [GET] - call_trace=C:\Python311\Lib\site-packages\flask\app.py L1414
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'getter' did not return a valid response. The function either returned None or ended without a return statement.
[2023-09-22 16:40:16,462] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:40:16] "[35m[1mGET /swagger?nome=Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaba HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-22 16:40:22,778] ERROR log_exception() L1414 Exception on /swagger [GET] - call_trace=C:\Python311\Lib\site-packages\flask\app.py L1414
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'getter' did not return a valid response. The function either returned None or ended without a return statement.
[2023-09-22 16:40:22,782] INFO _log() L187  127.0.0.1 - - [22/Sep/2023 16:40:22] "[35m[1mGET /swagger?nome=Harry%20Potter%20e%20o%20Prisioneiro%20de%20Azkaban HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
